# Generated by Django 5.0.7 on 2024-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_react'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='react',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Form Submissions'),
        ),
    ]
